### ISSUE TITLE
Output UMD?

### ISSUE THREAD

**Issue by inorganik** [kbysiec/vite-vanilla-ts-lib-starter#6]
Hey, I really like what you've got here! Prettier, jest, eslint, are all what I need. I maintain a library called [countUp](https://github.com/inorganik/countUp.js) and it currently uses gulp but I would like to modernize it. However I output a UMD module and an ES6 module, plus a separate bundle with a polyfill in it. Is there a way to customize the output to that level of granularity? I am still new to vite. Thanks.

**Comment by kbysiec** [comment]
Hi @inorganik,

sure, there is an option to do this in very easy way. The only thing you need to do is modify `vite.config.ts` file as the following:

```javascript
const fileName = {
  es: `${getPackageName()}.mjs`,
  cjs: `${getPackageName()}.cjs`,
  iife: `${getPackageName()}.iife.js`,
  umd: `${getPackageName()}.umd.js`,
} as const;
```

After adding `umd` the build will create the output for UMD module as well. If you do not any type, feel free to remove it.
I do not only know regarding adding polyfill to separate bundle because I haven't such a need, sorry.

Regards,
Kamil

**Comment by inorganik** [comment]
thanks!
